/**
 * Google Apps Script - Workshop Inbox Seeder (Lab 6.0)
 *
 * Sends the full TechBond sample inbox (30 emails) TO YOURSELF, so the
 * Module 6 live-connector labs have realistic data to work with.
 *
 * GENERATED FILE - do not edit by hand. Source templates live in
 * Seed-Emails/; regenerate with prep/scripts/generate_email_seeder.py.
 *
 * SETUP:
 * 1. Go to script.google.com
 * 2. Create new project
 * 3. Paste this entire script
 * 4. Run > testSendOneEmail (authorize when prompted, check your inbox)
 * 5. Run > sendAllEmails
 * 6. Check the Execution Log for progress
 */

const EMAILS = [
  { // 01-bondmax-inquiry.md
    subject: "RE: BondMax 500 bulk order inquiry",
    body: "**FROM:** purchasing@autoparts-inc.com\n**DATE:** January 02, 2026\n\n---\n\nHi TechBond Sales Team,\n\nFollowing up on our initial conversation about the BondMax 500 industrial adhesive.\n\nWe're looking to place a bulk order for our automotive assembly line. Our requirements:\n\n- **Quantity**: 500 units (25kg drums)\n- **Delivery**: Within 4 weeks to our Detroit facility\n- **Application**: Metal-to-metal bonding on chassis components\n\nCould you please provide:\n1. Volume pricing for this quantity\n2. Technical data sheet for BondMax 500\n3. Lead time confirmation\n4. Shipping options to Michigan, USA\n\nWe've been using a competitor product but are interested in switching due to your reputation for quality. Our engineering team has already tested samples and approved the product.\n\nLooking forward to your quote.\n\nBest regards,\n\n**Michael Torres**\nProcurement Manager\nAutoParts Inc.\npurchasing@autoparts-inc.com\n+1 (313) 555-0142"
  },
  { // 02-q4-sales-forecast.md
    subject: "Q4 Adhesives Sales Forecast - EMEA",
    body: "**FROM:** sales-director@techbond.com\n**DATE:** December 31, 2025\n\n---\n\nTeam,\n\nPlease find attached the Q4 sales forecast for our EMEA Adhesives division.\n\n**Key Highlights:**\n\n| Region | Q3 Actual | Q4 Target | YoY Growth |\n|--------|-----------|-----------|------------|\n| Germany | \u20ac4.2M | \u20ac4.8M | +12% |\n| France | \u20ac2.1M | \u20ac2.4M | +8% |\n| UK | \u20ac1.8M | \u20ac2.1M | +15% |\n| Nordics | \u20ac1.1M | \u20ac1.3M | +10% |\n\n**Priority Accounts for Q4:**\n1. MegaAuto Group - Contract renewal (\u20ac800K potential)\n2. AeroTech Supply - New aerospace qualification\n3. EuroDistributors - Expanded partnership agreement\n4. ChemCorp - Upsell SecureSeal EV series\n\n**Action Items:**\n- All account managers: Update pipeline in CRM by Friday\n- Regional leads: Submit revised forecasts by EOW\n- Technical sales: Schedule demos for SecureSeal EV launch\n\nLet's close the year strong. Q4 kickoff meeting scheduled for Monday.\n\nBest,\n\n**Sandra Mueller**\nSales Director, EMEA\nTechBond Industries"
  },
  { // 03-distributor-pricing.md
    subject: "Distributor pricing update request",
    body: "**FROM:** partner@euro-distributors.com\n**DATE:** January 03, 2026\n\n---\n\nDear TechBond Channel Team,\n\nAs we approach Q4, we'd like to discuss our 2026 distributor pricing agreement.\n\n**Current Status:**\n- 2025 sales volume: \u20ac2.3M (exceeded target by 8%)\n- Product mix: 60% BondMax series, 30% SecureSeal, 10% FlexiGrip\n- Geographic coverage: Germany, Austria, Switzerland\n\n**Our Request:**\nGiven our performance this year, we believe we qualify for Tier 1 distributor pricing. This would involve:\n\n1. Additional 5% volume discount\n2. Extended payment terms (Net 60)\n3. Priority allocation for new product launches\n4. Co-marketing fund increase\n\nWe're committed to growing our partnership and have already secured commitments from three new industrial accounts for 2026.\n\nCan we schedule a call next week to discuss? I'm available Tuesday or Wednesday afternoon.\n\nBest regards,\n\n**Hans Becker**\nManaging Director\nEuro Distributors GmbH\npartner@euro-distributors.com\n+49 89 555 0123"
  },
  { // 04-new-lead-tierone.md
    subject: "New automotive customer lead - TierOne Motors",
    body: "**FROM:** sales-rep@techbond.com\n**DATE:** January 04, 2026\n\n---\n\nHi Sandra,\n\nExciting news - we have a hot lead from TierOne Motors!\n\n**Lead Details:**\n- **Company**: TierOne Motors (Tier 1 automotive supplier)\n- **Contact**: Jennifer Walsh, VP Procurement\n- **Source**: Trade show follow-up from AutoExpo\n- **Potential**: \u20ac1.2M annual (estimated)\n\n**Requirements:**\n- High-temperature adhesive for EV battery assembly\n- Current supplier: AdhesiveCo (experiencing quality issues)\n- Timeline: Looking to qualify new supplier by Q1 2026\n- Volume: 50,000 units/month initially\n\n**Next Steps:**\n1. Technical demo scheduled for next Thursday\n2. Need samples shipped ASAP (requested SecureSeal EV series)\n3. Engineering team wants TDS and application guide\n\nThis could be our biggest new account of the year. Can you join the demo call?\n\nThanks,\n\n**Marcus Chen**\nSenior Sales Representative\nTechBond Industries"
  },
  { // 05-sample-request-evmotors.md
    subject: "Sample request: SecureSeal for EV battery testing",
    body: "**FROM:** procurement@evmotors.com\n**DATE:** January 01, 2026\n\n---\n\nHello TechBond Team,\n\nWe are EVMotors, an emerging electric vehicle manufacturer based in Munich.\n\nOur engineering team is evaluating adhesive solutions for our next-generation battery pack assembly. We would like to request samples of your SecureSeal EV series for testing.\n\n**Sample Request:**\n| Product | Quantity | Purpose |\n|---------|----------|---------|\n| SecureSeal EV-100 | 5 kg | Thermal interface bonding |\n| SecureSeal EV-200 | 5 kg | Structural cell bonding |\n| SecureSeal EV-300 | 2 kg | Potting compound testing |\n\n**Testing Timeline:**\n- Sample receipt: ASAP\n- Lab testing: 2 weeks\n- Production trial: Q1 2026 (if successful)\n\n**Technical Contact:**\nDr. Anna Schmidt\nBattery Engineering Lead\nanna.schmidt@evmotors.com\n\nPlease confirm sample availability and shipping timeline.\n\nBest regards,\n\n**Thomas Richter**\nProcurement Specialist\nEVMotors GmbH\nprocurement@evmotors.com"
  },
  { // 06-contract-renewal-chemcorp.md
    subject: "Contract renewal discussion - ChemCorp account",
    body: "**FROM:** account-manager@techbond.com\n**DATE:** December 30, 2025\n\n---\n\nHi Sandra,\n\nQuick update on the ChemCorp contract renewal.\n\n**Current Contract:**\n- Value: \u20ac650K annually\n- Products: BondMax 300, BondMax 500, FlexiGrip series\n- Expiration: December 31, 2025\n\n**Renewal Discussion:**\nMet with their procurement team yesterday. Key points:\n\n1. **They want to expand** - interested in adding SecureSeal products\n2. **Price pressure** - requesting 8% reduction due to \"market conditions\"\n3. **Competitor threat** - AdhesiveCo has been actively pursuing them\n4. **Opportunity** - New plant opening in Poland needs supplier qualification\n\n**Proposed Response:**\n- Offer 3% volume discount (not 8%)\n- Bundle SecureSeal introduction at promotional pricing\n- Fast-track Poland facility qualification\n- Extended 3-year agreement vs. annual renewal\n\n**Financials:**\n- Current: \u20ac650K/year\n- Proposed: \u20ac750K/year (with expansion)\n- Risk if lost: Major account reference in chemical sector\n\nCan we discuss strategy before my follow-up call on Thursday?\n\nThanks,\n\n**Lisa Park**\nKey Account Manager\nTechBond Industries"
  },
  { // 07-competitor-alert.md
    subject: "Competitor pricing alert - AdhesiveCo undercutting",
    body: "**FROM:** market-intel@techbond.com\n**DATE:** January 02, 2026\n\n---\n\n**COMPETITIVE INTELLIGENCE ALERT**\n\nTeam,\n\nWe've received reports that AdhesiveCo is aggressively targeting our key accounts with below-market pricing.\n\n**Situation:**\n- AdhesiveCo offering 15-20% discounts to win TechBond accounts\n- Confirmed approaches to: MegaAuto, ChemCorp, AutoParts Inc.\n- Pricing appears unsustainable (likely loss-leader strategy)\n\n**Affected Products:**\n| Our Product | Their Equivalent | Their Discount |\n|-------------|------------------|----------------|\n| BondMax 500 | AdhesiMax Pro | 18% below our price |\n| SecureSeal 100 | SecureBond EV | 15% below our price |\n\n**Recommended Response:**\n1. **DO NOT** match pricing directly\n2. Emphasize quality differentiation (attach comparison data)\n3. Offer value-added services (extended warranty, technical support)\n4. Accelerate customer success stories and case studies\n\n**Action Required:**\n- Account managers: Contact at-risk accounts proactively\n- Schedule customer visits within next 2 weeks\n- Report any competitive quotes received\n\nFull competitive analysis report attached.\n\n**Market Intelligence Team**\nTechBond Industries"
  },
  { // 08-technical-specs-aerospace.md
    subject: "Technical specs needed for aerospace application",
    body: "**FROM:** engineer@aerotech-supply.com\n**DATE:** January 03, 2026\n\n---\n\nHello TechBond Technical Team,\n\nWe are AeroTech Supply, a certified aerospace component supplier.\n\nWe're evaluating your BondMax 700 high-performance adhesive for use in aircraft interior panel assembly. Before we can proceed with qualification, we need additional technical documentation.\n\n**Required Documentation:**\n1. Full technical data sheet with aerospace specifications\n2. Outgassing test results (ASTM E595)\n3. Flame/smoke/toxicity (FST) certification\n4. Long-term durability data (10,000+ hour aging tests)\n5. Temperature cycling performance (-55\u00b0C to +85\u00b0C)\n\n**Application Details:**\n- Use case: Interior panel bonding (galley, lavatory, overhead bins)\n- Substrates: Aluminum honeycomb to composite face sheets\n- Required certifications: FAA, EASA compliance\n\n**Timeline:**\n- Documentation review: 2 weeks\n- Sample testing: 4 weeks\n- Qualification decision: Q1 2026\n\nPlease let us know if BondMax 700 has aerospace qualifications or if you recommend a different product from your portfolio.\n\nBest regards,\n\n**Dr. Robert Kim**\nMaterials Engineer\nAeroTech Supply Inc.\nengineer@aerotech-supply.com\n+1 (206) 555-0198"
  },
  { // 09-volume-discount-megaauto.md
    subject: "Volume discount negotiation follow-up",
    body: "**FROM:** purchasing@megaauto.com\n**DATE:** January 04, 2026\n\n---\n\nDear TechBond Sales Team,\n\nThank you for the meeting last week to discuss our 2026 supply agreement.\n\nFollowing our internal review, I'd like to summarize our position:\n\n**Current Annual Spend:** \u20ac1.8M\n**Proposed 2026 Spend:** \u20ac2.4M (+33% increase)\n\n**Our Expectations:**\nGiven the significant volume increase, we expect:\n\n| Volume Tier | Discount Expected |\n|-------------|-------------------|\n| \u20ac1.8M - \u20ac2.0M | 8% |\n| \u20ac2.0M - \u20ac2.4M | 12% |\n| >\u20ac2.4M | 15% |\n\n**Additional Terms:**\n- Quarterly price review mechanism\n- Safety stock held at TechBond warehouse\n- Dedicated technical support engineer\n- Priority in case of allocation constraints\n\n**Competitive Context:**\nWe have received competitive quotes from AdhesiveCo and BondMaster that are 10-12% below your current pricing. However, we value our relationship and quality track record with TechBond.\n\nPlease respond with your best offer by end of week. Our procurement committee meets next Monday.\n\nRegards,\n\n**David Mueller**\nVP Procurement\nMegaAuto Group\npurchasing@megaauto.com"
  },
  { // 10-sales-achievement.md
    subject: "Sales target achievement - Q3 congratulations!",
    body: "**FROM:** regional-director@techbond.com\n**DATE:** December 29, 2025\n\n---\n\nTeam EMEA,\n\nI'm thrilled to announce that we have **exceeded our Q3 sales target by 12%**!\n\n**Q3 Results:**\n\n| Metric | Target | Actual | Achievement |\n|--------|--------|--------|-------------|\n| Revenue | \u20ac9.0M | \u20ac10.1M | 112% |\n| New Accounts | 15 | 19 | 127% |\n| Renewal Rate | 85% | 91% | 107% |\n| Avg Deal Size | \u20ac45K | \u20ac52K | 116% |\n\n**Top Performers:**\n1. **Marcus Chen** - \u20ac1.4M (TierOne Motors progress)\n2. **Lisa Park** - \u20ac1.2M (ChemCorp expansion)\n3. **Johan Eriksson** - \u20ac980K (Nordic region growth)\n\n**Special Recognition:**\n- Best New Account: EVMotors qualification (Thomas's team)\n- Best Save: MegaAuto retention (entire team effort)\n- Most Improved: UK region (+22% YoY)\n\n**Celebration:**\nTeam dinner scheduled for Friday at 7 PM - details to follow.\n\n**Looking Ahead:**\nQ4 is our biggest quarter. With momentum from Q3 and the SecureSeal EV launch, we're positioned for a record year.\n\nThank you all for your dedication and hard work!\n\n**Klaus Weber**\nRegional Director, EMEA\nTechBond Industries"
  },
  { // 11-glossstyle-campaign.md
    subject: "GlossStyle Professional campaign results",
    body: "**FROM:** marketing@techbond.com\n**DATE:** January 01, 2026\n\n---\n\nHi Brand Team,\n\nHere are the final results from our GlossStyle Professional Q3 campaign.\n\n**Campaign Overview:**\n- **Duration**: July 1 - September 30\n- **Target**: Professional hair stylists and salons\n- **Budget**: \u20ac180K\n- **Channels**: Digital ads, trade publications, salon partnerships\n\n**Results:**\n\n| Metric | Target | Actual | Performance |\n|--------|--------|--------|-------------|\n| Impressions | 5M | 6.2M | 124% |\n| Click-through rate | 2.0% | 2.4% | 120% |\n| Lead generation | 800 | 1,050 | 131% |\n| Salon sign-ups | 150 | 187 | 125% |\n| Cost per lead | \u20ac225 | \u20ac171 | 132% (under budget) |\n\n**Top Performing Content:**\n1. \"Transform Your Salon\" video - 2.1M views\n2. Before/after Instagram carousel - 89K engagements\n3. Professional tips blog series - 45K unique visitors\n\n**Key Learnings:**\n- Video content significantly outperformed static images\n- Instagram Stories drove highest engagement with salon owners\n- Trade publication ads had lower ROI than digital\n\n**Recommendations for Q4:**\n- Increase video budget by 30%\n- Launch TikTok presence for younger stylists\n- Partner with 3 additional influencer stylists\n\nFull report attached.\n\n**Emma Rodriguez**\nMarketing Manager, Consumer Brands\nTechBond Industries"
  },
  { // 12-cleanwave-sustainability.md
    subject: "CleanWave sustainability messaging review",
    body: "**FROM:** brand-manager@techbond.com\n**DATE:** January 02, 2026\n\n---\n\nTeam,\n\nWe need to review and approve the new sustainability messaging for CleanWave before the Q4 campaign launch.\n\n**Background:**\nConsumer research shows 73% of our target demographic considers environmental impact when purchasing cleaning products. Our current messaging doesn't adequately communicate CleanWave's sustainability features.\n\n**Proposed Messaging Updates:**\n\n**Current Tagline:** \"CleanWave - Power Clean for Every Home\"\n\n**Proposed Tagline:** \"CleanWave - Clean Home, Clean Planet\"\n\n**Key Messages:**\n1. \"90% biodegradable formula\"\n2. \"100% recycled plastic bottles\"\n3. \"Carbon-neutral manufacturing\"\n4. \"Concentrated formula = less packaging\"\n\n**Concerns to Address:**\n- Legal review of \"biodegradable\" claims - need documentation\n- Verify carbon-neutral certification timeline\n- Ensure messaging aligns with corporate sustainability report\n\n**Review Needed By:**\n- **Legal**: Claim verification\n- **Sustainability Team**: Accuracy check\n- **Creative**: Visual execution concepts\n- **PR**: Media talking points alignment\n\n**Deadline:** Please provide feedback by Friday EOD.\n\nCampaign launch scheduled for November 1st.\n\nThanks,\n\n**Sarah Chen**\nBrand Manager, CleanWave\nTechBond Industries"
  },
  { // 13-tradeshow-booth.md
    subject: "Trade show booth design approval needed",
    body: "**FROM:** events@techbond.com\n**DATE:** December 31, 2025\n\n---\n\nHi Team,\n\nWe need final approval on the AutoExpo 2025 booth design by end of week.\n\n**Event Details:**\n- **Event**: AutoExpo 2025\n- **Dates**: November 15-18\n- **Location**: Frankfurt Messe, Hall 4\n- **Booth Size**: 60 sqm (corner location)\n\n**Booth Design Concept:**\n\"The Future of Automotive Bonding\"\n\n**Key Features:**\n1. **Interactive Demo Station** - Live SecureSeal EV application\n2. **Product Display Wall** - Full adhesive portfolio\n3. **Meeting Pod** - 4 private meeting spaces\n4. **Digital Experience** - AR visualization of bond strength\n5. **Sustainability Corner** - Environmental certifications\n\n**Budget Breakdown:**\n\n| Item | Cost |\n|------|------|\n| Booth construction | \u20ac45,000 |\n| Graphics & signage | \u20ac12,000 |\n| AV equipment | \u20ac8,000 |\n| Furniture rental | \u20ac5,000 |\n| Demo materials | \u20ac10,000 |\n| **Total** | **\u20ac80,000** |\n\n**Approvals Needed:**\n- [ ] Design concept - Marketing Director\n- [ ] Budget - Finance\n- [ ] Messaging - Brand Team\n- [ ] Demo products - R&D\n\nDesign mockups attached. Please review and confirm.\n\n**Michelle Lee**\nEvents Manager\nTechBond Industries"
  },
  { // 14-social-media-performance.md
    subject: "Social media performance - Adhesives B2B Q3",
    body: "**FROM:** digital-marketing@techbond.com\n**DATE:** January 03, 2026\n\n---\n\nTeam,\n\nQ3 social media performance report for our B2B Adhesives division.\n\n**Platform Summary:**\n\n| Platform | Followers | Growth | Engagement Rate |\n|----------|-----------|--------|-----------------|\n| LinkedIn | 45,200 | +12% | 4.2% |\n| YouTube | 8,500 | +25% | 6.8% |\n| Twitter/X | 12,100 | +5% | 1.8% |\n\n**Top Performing Content:**\n\n**LinkedIn:**\n1. \"5 Common Adhesive Application Mistakes\" - 12K views, 890 engagements\n2. Customer success story: MegaAuto - 8K views, 560 engagements\n3. SecureSeal EV teaser video - 15K views, 1,200 engagements\n\n**YouTube:**\n1. \"BondMax Application Tutorial\" - 45K views\n2. \"Automotive Adhesive Testing Process\" - 32K views\n3. Factory tour video - 28K views\n\n**Key Insights:**\n- Educational content drives 3x more engagement than product posts\n- Video content averages 40% higher engagement than images\n- Best posting times: Tuesday-Thursday, 9-11 AM CET\n\n**Q4 Content Calendar Highlights:**\n- SecureSeal EV launch campaign (Nov 1)\n- AutoExpo live coverage (Nov 15-18)\n- Year-in-review video series (Dec)\n\n**Recommendations:**\n- Increase LinkedIn video budget\n- Launch technical webinar series\n- Partner with industry influencers\n\n**Alex Thompson**\nDigital Marketing Specialist\nTechBond Industries"
  },
  { // 15-secureseal-launch-timeline.md
    subject: "New product launch timeline - SecureSeal EV Series",
    body: "**FROM:** product-marketing@techbond.com\n**DATE:** December 30, 2025\n\n---\n\nTeam,\n\nFinal launch timeline for SecureSeal EV Series - our new adhesive line for electric vehicle manufacturing.\n\n**Product Overview:**\n- SecureSeal EV-100: Thermal interface bonding\n- SecureSeal EV-200: Structural cell bonding\n- SecureSeal EV-300: Potting and encapsulation\n\n**Launch Timeline:**\n\n| Date | Milestone | Owner |\n|------|-----------|-------|\n| Oct 15 | Final product specs approved | R&D |\n| Oct 20 | Sales training materials ready | Product Marketing |\n| Oct 25 | Press release draft finalized | PR |\n| Oct 28 | Website product pages live | Digital |\n| Nov 1 | **OFFICIAL LAUNCH** | All |\n| Nov 1-7 | Email campaign to prospects | Marketing |\n| Nov 15 | AutoExpo showcase | Events |\n| Nov 30 | Post-launch review | All |\n\n**Launch Day Activities (Nov 1):**\n- Press release distribution - 6 AM CET\n- Social media announcement - 8 AM CET\n- Customer email blast - 9 AM CET\n- Sales team webinar - 10 AM CET\n- Partner notification - 11 AM CET\n\n**Materials Status:**\n- [x] Technical data sheets\n- [x] Product brochures\n- [x] Sales presentation\n- [ ] Demo video (due Oct 28)\n- [ ] Application guide (due Oct 25)\n\n**Critical Dependencies:**\n- R&D sign-off on final specs\n- Legal approval on claims\n- Sample inventory at warehouse\n\nPlease confirm your team's readiness by replying to this email.\n\n**Jennifer Walsh**\nProduct Marketing Manager\nTechBond Industries"
  },
  { // 16-testimonial-video.md
    subject: "Customer testimonial video approval",
    body: "**FROM:** content@techbond.com\n**DATE:** January 04, 2026\n\n---\n\nHi Team,\n\nThe customer testimonial video with MegaAuto is ready for review and approval.\n\n**Video Details:**\n- **Customer**: MegaAuto Group\n- **Spokesperson**: Dr. Klaus Hoffman, VP Manufacturing\n- **Duration**: 3:45 minutes\n- **Format**: Professional studio quality\n\n**Key Quotes:**\n> \"TechBond's BondMax adhesive reduced our assembly time by 30% while improving joint strength.\"\n\n> \"The technical support team helped us optimize our application process within two weeks.\"\n\n> \"We've been partners for 5 years and the quality consistency is unmatched in the industry.\"\n\n**Planned Usage:**\n- Website customer stories page\n- LinkedIn campaign\n- Sales presentations\n- Trade show booth display\n- YouTube channel\n\n**Review Checklist:**\n- [ ] Customer approved final cut\n- [ ] Legal review complete\n- [ ] Brand guidelines compliance\n- [ ] Music licensing confirmed\n- [ ] Subtitles/captions added\n\n**Deadline for Feedback:** Thursday EOD\n\nVideo link: [Internal review link]\n\nPassword: TechBond2025\n\n**Rachel Green**\nContent Marketing Manager\nTechBond Industries"
  },
  { // 17-press-release-award.md
    subject: "Press release draft - Innovation Award",
    body: "**FROM:** pr@techbond.com\n**DATE:** January 01, 2026\n\n---\n\nTeam,\n\nPlease review the press release draft for our Chemical Industry Innovation Award.\n\n---\n\n**FOR IMMEDIATE RELEASE**\n\n**TechBond Industries Wins 2025 Chemical Industry Innovation Award for SecureSeal EV Technology**\n\n*Revolutionary adhesive solution for electric vehicle battery manufacturing recognized by industry peers*\n\n**DUSSELDORF, GERMANY** - TechBond Industries today announced it has been awarded the prestigious 2025 Chemical Industry Innovation Award for its SecureSeal EV series of adhesives, designed specifically for electric vehicle battery assembly.\n\nThe award, presented by the European Chemical Industry Council, recognizes TechBond's breakthrough in developing high-performance, thermally conductive adhesives that address the unique challenges of EV battery manufacturing.\n\n\"We are honored to receive this recognition,\" said [CEO Name], CEO of TechBond Industries. \"The SecureSeal EV series represents years of research and development focused on supporting the automotive industry's transition to electric mobility.\"\n\n**Key Innovations:**\n- 40% improvement in thermal conductivity vs. market alternatives\n- Reduced assembly time by 25%\n- 100% compliance with automotive OEM specifications\n- Sustainable formulation with reduced VOC emissions\n\nThe SecureSeal EV series is already being evaluated by major automotive manufacturers and is scheduled for commercial launch on November 1, 2025.\n\n**About TechBond Industries**\n[Company boilerplate]\n\n**Media Contact:**\n[PR Contact Name]\npr@techbond.com\n\n---\n\nPlease provide feedback by Wednesday for Thursday distribution.\n\n**Maria Santos**\nPR Manager\nTechBond Industries"
  },
  { // 18-email-campaign-results.md
    subject: "Email campaign A/B test results - October",
    body: "**FROM:** marketing-ops@techbond.com\n**DATE:** January 03, 2026\n\n---\n\nTeam,\n\nHere are the A/B test results from our October email campaigns.\n\n**Test 1: Subject Line Testing**\nCampaign: Monthly Newsletter\n\n| Version | Subject Line | Open Rate |\n|---------|--------------|-----------|\n| A | \"TechBond October Newsletter\" | 22.3% |\n| B | \"5 Adhesive Tips That Could Save You Thousands\" | 34.7% |\n| **Winner** | Version B | **+55% improvement** |\n\n**Test 2: CTA Button Color**\nCampaign: SecureSeal Teaser\n\n| Version | Button Color | Click Rate |\n|---------|--------------|------------|\n| A | Blue (brand color) | 4.2% |\n| B | Orange (contrast) | 5.8% |\n| **Winner** | Version B | **+38% improvement** |\n\n**Test 3: Send Time**\nCampaign: Product Update\n\n| Version | Send Time | Open Rate |\n|---------|-----------|-----------|\n| A | Tuesday 9 AM | 28.1% |\n| B | Thursday 2 PM | 31.4% |\n| **Winner** | Version B | **+12% improvement** |\n\n**Overall Campaign Performance:**\n\n| Metric | September | October | Change |\n|--------|-----------|---------|--------|\n| Avg Open Rate | 24.5% | 29.8% | +22% |\n| Avg Click Rate | 3.8% | 5.1% | +34% |\n| Unsubscribe Rate | 0.4% | 0.3% | -25% |\n\n**Recommendations for November:**\n1. Use benefit-driven subject lines (not generic)\n2. Test orange CTAs on promotional emails\n3. Schedule key campaigns for Thursday afternoons\n\n**Daniel Kim**\nMarketing Operations\nTechBond Industries"
  },
  { // 19-influencer-proposal.md
    subject: "Influencer partnership proposal - Hair care line",
    body: "**FROM:** partnerships@techbond.com\n**DATE:** January 02, 2026\n\n---\n\nHi Sarah,\n\nI've identified a potential influencer partnership opportunity for GlossStyle.\n\n**Influencer Profile:**\n\n**Name**: Julia Styling (@juliastyling)\n**Platform**: Instagram, TikTok, YouTube\n**Followers**:\n- Instagram: 450K\n- TikTok: 890K\n- YouTube: 120K\n\n**Audience Demographics:**\n- 78% female, 22% male\n- Age: 25-44 (primary)\n- Location: 60% Europe, 25% US, 15% other\n- Interest: Hair care, salon professionals, beauty\n\n**Content Style:**\n- Professional salon tutorials\n- Product reviews and comparisons\n- Behind-the-scenes salon content\n- Hair transformation videos\n\n**Engagement Rate:** 5.2% (above industry average of 3.5%)\n\n**Proposed Partnership:**\n\n| Deliverable | Quantity | Estimated Reach |\n|-------------|----------|-----------------|\n| Instagram posts | 4 | 1.8M |\n| Instagram Stories | 8 | 900K |\n| TikTok videos | 3 | 2.5M |\n| YouTube feature | 1 | 150K |\n\n**Investment:** \u20ac25,000 for 3-month campaign\n\n**Timeline:** November - January (peak salon season)\n\n**ROI Projection:**\n- Expected reach: 5.35M impressions\n- Estimated CPM: \u20ac4.67\n- Projected new followers: 15K\n- Estimated sales impact: \u20ac75K-100K\n\nShould I proceed with initial outreach?\n\n**Amanda Foster**\nPartnerships Manager\nTechBond Industries"
  },
  { // 20-brand-guidelines-update.md
    subject: "Brand guidelines update notification",
    body: "**FROM:** brand@techbond.com\n**DATE:** December 31, 2025\n\n---\n\nDear Marketing Team,\n\nPlease be advised that updated brand guidelines are now available.\n\n**What's Changed:**\n\n**1. Logo Usage**\n- New minimum size requirements for digital applications\n- Updated clear space specifications\n- Added guidelines for dark mode/backgrounds\n\n**2. Color Palette**\n- Added secondary accent colors for digital campaigns\n- Updated accessibility guidelines (WCAG 2.1 compliance)\n- New gradient specifications for social media\n\n**3. Typography**\n- Primary font updated to \"TechBond Sans\" (download required)\n- New web font guidelines\n- Updated size hierarchy for presentations\n\n**4. Photography Style**\n- New direction: More authentic, less stock-photo feel\n- Updated guidance on image treatments\n- New library of approved photography\n\n**5. Brand Voice**\n- Refined tone guidelines for B2B vs. Consumer communications\n- New examples for social media\n- Updated competitor differentiation language\n\n**Action Required:**\n1. Download updated brand guidelines from Brand Portal\n2. Update any templates you use regularly\n3. Attend brand refresh webinar (Oct 25, 2 PM)\n4. Direct questions to brand@techbond.com\n\n**Transition Period:**\n- Current materials can be used until December 31, 2025\n- All new materials from January 1, 2026 must follow new guidelines\n\n**Resources:**\n- Brand Portal: [Internal link]\n- Font download: [Internal link]\n- Template library: [Internal link]\n\n**Brand Team**\nTechBond Industries"
  },
  { // 21-lab-test-results.md
    subject: "Lab test results: Batch TB-2025-1547",
    body: "**FROM:** lab@techbond.com\n**DATE:** January 02, 2026\n\n---\n\nQuality and Production Teams,\n\nLab testing for Batch TB-2025-1547 (BondMax 500) has been completed.\n\n**Batch Information:**\n- Product: BondMax 500\n- Batch Number: TB-2025-1547\n- Production Date: October 5, 2025\n- Quantity: 5,000 kg\n\n**Test Results:**\n\n| Parameter | Specification | Result | Status |\n|-----------|---------------|--------|--------|\n| Viscosity (25\u00b0C) | 2500-3500 cP | 2980 cP | PASS |\n| Density | 1.05-1.10 g/cm\u00b3 | 1.07 g/cm\u00b3 | PASS |\n| Tensile Strength | >15 MPa | 18.2 MPa | PASS |\n| Shear Strength | >12 MPa | 14.5 MPa | PASS |\n| Cure Time (RT) | <24 hours | 18 hours | PASS |\n| Color | Light amber | Light amber | PASS |\n| Shelf Life Test | 12 months | Ongoing | - |\n\n**Quality Assessment:** **APPROVED FOR RELEASE**\n\nAll parameters meet or exceed specifications. Batch is cleared for customer shipment.\n\n**Retention Samples:**\n- 3 samples retained for 24-month archival\n- Location: Lab Storage Room B, Shelf 12\n\n**Certificate of Analysis:** Attached\n\nPlease confirm inventory release.\n\n**Dr. Maria Fischer**\nLaboratory Manager\nTechBond Industries R&D"
  },
  { // 22-quality-incident.md
    subject: "Quality incident report - Production line 3",
    body: "**FROM:** quality@techbond.com\n**DATE:** January 03, 2026\n\n---\n\n**QUALITY INCIDENT NOTIFICATION**\n\n**Incident ID:** QI-2025-0087\n**Severity:** Medium\n**Status:** Under Investigation\n\n**Incident Summary:**\nDuring routine quality check, viscosity deviation detected on Production Line 3 for SecureSeal 100 batch SS-2025-892.\n\n**Details:**\n\n| Field | Information |\n|-------|-------------|\n| Date/Time | October 7, 2025, 14:35 |\n| Product | SecureSeal 100 |\n| Batch | SS-2025-892 |\n| Affected Quantity | 2,000 kg |\n| Detection Point | In-process QC check |\n\n**Deviation:**\n- Specification: Viscosity 1800-2200 cP\n- Measured: 2450 cP (11% above upper limit)\n\n**Immediate Actions Taken:**\n1. Production line 3 halted\n2. Batch quarantined - DO NOT SHIP\n3. Raw material samples collected for testing\n4. Equipment calibration check initiated\n\n**Root Cause Analysis (Preliminary):**\n- Suspected: Temperature control malfunction in mixing tank\n- Alternative: Raw material variation from new supplier batch\n\n**Investigation Timeline:**\n- Root cause determination: 48 hours\n- Corrective action plan: 72 hours\n- Full report: 1 week\n\n**Impact Assessment:**\n- Customer shipments: 2 orders may be delayed (MegaAuto, ChemCorp)\n- Financial: Estimated \u20ac15K batch loss if not reworkable\n\n**Required Actions:**\n- Production: Hold all Line 3 output pending investigation\n- Sales: Notify affected customers of potential delay\n- Procurement: Verify raw material certificates\n\n**Stefan Braun**\nQuality Assurance Manager\nTechBond Industries"
  },
  { // 23-supplier-delay.md
    subject: "Supplier delivery delay notification",
    body: "**FROM:** logistics@rawchem-supplier.com\n**DATE:** January 01, 2026\n\n---\n\nDear TechBond Procurement Team,\n\nWe regret to inform you of a delivery delay affecting your upcoming order.\n\n**Order Details:**\n- Order Number: PO-2025-4521\n- Products: Epoxy Resin ER-500, Hardener H-200\n- Original Delivery Date: October 12, 2025\n- **Revised Delivery Date: October 19, 2025**\n\n**Reason for Delay:**\nUnexpected equipment maintenance at our primary production facility has impacted our manufacturing schedule. We are working around the clock to minimize the delay.\n\n**Affected Items:**\n\n| Product | Quantity | Original Date | New Date |\n|---------|----------|---------------|----------|\n| Epoxy Resin ER-500 | 10,000 kg | Oct 12 | Oct 19 |\n| Hardener H-200 | 5,000 kg | Oct 12 | Oct 19 |\n\n**Impact Mitigation:**\n- We can provide partial shipment (40%) by October 14\n- Expedited shipping at no additional cost\n- Priority allocation from our Rotterdam warehouse\n\n**Alternative Options:**\n1. Accept partial shipment + delayed remainder\n2. Full shipment on October 19\n3. Source from alternative RawChem facility (contact us for availability)\n\n**Compensation:**\nAs per our service agreement, we will apply a 3% credit to this order due to the delay.\n\nPlease confirm your preferred option by tomorrow EOD.\n\nWe apologize for any inconvenience caused.\n\n**Peter Schmidt**\nCustomer Service Manager\nRawChem Supplier GmbH\nlogistics@rawchem-supplier.com\n+49 221 555 0456"
  },
  { // 24-ehs-audit.md
    subject: "EHS compliance audit scheduled - November",
    body: "**FROM:** compliance@techbond.com\n**DATE:** December 31, 2025\n\n---\n\nAll Dusseldorf Site Personnel,\n\nPlease be advised that our annual EHS (Environment, Health & Safety) compliance audit is scheduled for November.\n\n**Audit Details:**\n\n| Field | Information |\n|-------|-------------|\n| Audit Type | ISO 14001 & ISO 45001 Surveillance |\n| Auditor | T\u00dcV Rheinland |\n| Dates | November 11-13, 2025 |\n| Scope | All Dusseldorf operations |\n\n**Audit Schedule:**\n\n**Day 1 (Nov 11):**\n- Opening meeting\n- Management review\n- Documentation review\n\n**Day 2 (Nov 12):**\n- Production area walkthrough\n- Laboratory inspection\n- Warehouse and logistics\n\n**Day 3 (Nov 13):**\n- Employee interviews\n- Closing meeting\n- Preliminary findings\n\n**Preparation Required:**\n\n**All Departments:**\n- [ ] Review and update department procedures\n- [ ] Ensure training records are current\n- [ ] Complete workplace inspections\n- [ ] Address any open corrective actions\n\n**Production:**\n- [ ] Verify chemical storage compliance\n- [ ] Check PPE availability and condition\n- [ ] Update equipment maintenance logs\n\n**Laboratory:**\n- [ ] Review hazardous waste disposal records\n- [ ] Verify emergency equipment inspection dates\n- [ ] Update chemical inventory\n\n**Pre-Audit Checklist:** See attached\n\n**Questions?** Contact the EHS team at compliance@techbond.com\n\n**Andreas M\u00fcller**\nEHS Manager\nTechBond Industries"
  },
  { // 25-it-maintenance.md
    subject: "IT system maintenance - Saturday downtime",
    body: "**FROM:** it@techbond.com\n**DATE:** January 04, 2026\n\n---\n\nDear Colleagues,\n\nPlanned IT system maintenance will occur this Saturday.\n\n**Maintenance Window:**\n- **Date:** Saturday, October 12, 2025\n- **Time:** 22:00 - 06:00 CET (Sunday)\n- **Duration:** 8 hours\n\n**Affected Systems:**\n\n| System | Downtime | Impact |\n|--------|----------|--------|\n| Email (Outlook) | 22:00-02:00 | No email access |\n| ERP System | 22:00-06:00 | No order processing |\n| SharePoint | 23:00-03:00 | No document access |\n| VPN | 00:00-04:00 | No remote access |\n| CRM | 01:00-05:00 | No customer data access |\n\n**What We're Doing:**\n- Security patches and updates\n- Database optimization\n- Server hardware upgrades\n- Backup system improvements\n\n**What You Need to Do:**\n\n**Before Saturday:**\n- Save any work in progress locally\n- Complete any urgent ERP transactions by Friday 5 PM\n- Download any documents you may need over the weekend\n\n**During Maintenance:**\n- Systems will be unavailable - please do not attempt to access\n- Mobile email may work intermittently - not guaranteed\n- Emergency IT support: +49 211 555 0999\n\n**After Maintenance:**\n- All systems expected online by Sunday 6 AM\n- If you experience issues, restart your computer first\n- Report persistent issues to IT Service Desk\n\n**Why Saturday Night?**\nScheduling maintenance during lowest-usage period minimizes business impact while allowing adequate time for updates.\n\nThank you for your patience.\n\n**IT Department**\nTechBond Industries"
  },
  { // 26-erp-training.md
    subject: "Training: New ERP module rollout",
    body: "**FROM:** hr-training@techbond.com\n**DATE:** December 30, 2025\n\n---\n\nDear Colleagues,\n\nWe are rolling out a new ERP module and training is mandatory for all affected users.\n\n**New Module:** Advanced Order Management (AOM)\n\n**What's New:**\n- Real-time inventory visibility across all warehouses\n- Automated delivery date calculation\n- Customer credit check integration\n- Enhanced reporting dashboard\n\n**Training Schedule:**\n\n| Session | Date | Time | Location | Target Audience |\n|---------|------|------|----------|-----------------|\n| Session 1 | Oct 15 | 9:00-12:00 | Training Room A | Sales Team |\n| Session 2 | Oct 15 | 14:00-17:00 | Training Room A | Order Processing |\n| Session 3 | Oct 16 | 9:00-12:00 | Training Room B | Warehouse Staff |\n| Session 4 | Oct 16 | 14:00-17:00 | Virtual | Remote Users |\n\n**Registration Required:**\nPlease register for your session by October 11:\n[Registration Link]\n\n**Pre-Training Tasks:**\n1. Review the attached user guide (30 min read)\n2. Complete online pre-assessment quiz\n3. Ensure ERP login credentials are working\n\n**Go-Live Date:** November 1, 2025\n\n**Support After Go-Live:**\n- Super users available in each department\n- IT Help Desk extended hours (first 2 weeks)\n- Online documentation and FAQs\n\n**Questions?**\nContact: training@techbond.com\n\n**Julia Weber**\nHR Training Coordinator\nTechBond Industries"
  },
  { // 27-budget-approval.md
    subject: "Budget approval request - R&D equipment",
    body: "**FROM:** finance@techbond.com\n**DATE:** January 02, 2026\n\n---\n\nDr. Fischer,\n\nFollowing up on your capital expenditure request for R&D laboratory equipment.\n\n**Request Summary:**\n\n| Item | Description | Amount |\n|------|-------------|--------|\n| Rheometer | TA Instruments DHR-3 | \u20ac85,000 |\n| Tensile Tester | Instron 5967 | \u20ac62,000 |\n| Thermal Analyzer | TA Q2000 DSC | \u20ac48,000 |\n| Installation | Professional setup | \u20ac12,000 |\n| Training | Operator certification | \u20ac8,000 |\n| **Total** | | **\u20ac215,000** |\n\n**Budget Status:**\n- 2025 R&D CapEx Budget: \u20ac500,000\n- Spent YTD: \u20ac320,000\n- Remaining: \u20ac180,000\n- **This Request: \u20ac215,000**\n- **Shortfall: \u20ac35,000**\n\n**Options:**\n\n**Option A:** Defer thermal analyzer to 2026\n- 2025 spend: \u20ac167,000 (within budget)\n- Thermal analyzer in Q1 2026 budget\n\n**Option B:** Request budget increase\n- Requires VP Finance approval\n- Justification: SecureSeal EV testing requirements\n- Timeline: 2 weeks for approval process\n\n**Option C:** Lease instead of purchase\n- Monthly cost: \u20ac4,200/month for 5 years\n- Total cost: \u20ac252,000 (higher overall)\n- No 2025 CapEx impact\n\n**Required Documentation for Option B:**\n1. Business case with ROI analysis\n2. Testing volume projections\n3. Alternative vendor quotes (min 2)\n\nPlease advise on preferred approach.\n\n**Thomas Schulz**\nFinance Controller\nTechBond Industries"
  },
  { // 28-patent-status.md
    subject: "Patent filing status update - FlexiGrip formula",
    body: "**FROM:** legal@techbond.com\n**DATE:** January 01, 2026\n\n---\n\nDear Leadership Team,\n\nUpdate on the patent filing for our new FlexiGrip adhesive formulation.\n\n**Patent Application Details:**\n- **Title:** \"High-Flexibility Adhesive Composition for Electronic Component Assembly\"\n- **Application Number:** EP2025/078542\n- **Filing Date:** September 15, 2025\n- **Jurisdiction:** European Patent Office (EPO)\n\n**Status Timeline:**\n\n| Milestone | Date | Status |\n|-----------|------|--------|\n| Initial filing | Sep 15, 2025 | Complete |\n| Formality check | Oct 1, 2025 | Passed |\n| Prior art search | Oct 15, 2025 (est) | In Progress |\n| Publication | Mar 2026 (est) | Pending |\n| Examination | Q3 2026 (est) | Pending |\n| Grant decision | Q4 2026 (est) | Pending |\n\n**Claim Summary:**\n1. Novel polymer blend composition\n2. Curing mechanism at low temperatures\n3. Flexibility retention after thermal cycling\n4. Application method for fine-pitch electronics\n\n**Parallel Filings:**\n- US provisional filed (Oct 1, 2025)\n- PCT application planned (March 2026)\n- China/Japan filings planned (Q2 2026)\n\n**Cost Summary:**\n- EPO filing: \u20ac15,000 (paid)\n- US provisional: \u20ac3,500 (paid)\n- PCT estimated: \u20ac25,000\n- Total 2025: \u20ac18,500\n- Total projected: \u20ac80,000-100,000\n\n**Confidentiality Reminder:**\nUntil publication, please limit disclosure of formulation details to need-to-know basis.\n\n**Dr. Helena Kraus**\nIntellectual Property Counsel\nTechBond Industries"
  },
  { // 29-employee-survey.md
    subject: "Employee engagement survey results",
    body: "**FROM:** hr@techbond.com\n**DATE:** January 03, 2026\n\n---\n\nDear Managers,\n\nThe 2025 Employee Engagement Survey results are now available.\n\n**Participation:**\n- Total responses: 847 (out of 980 employees)\n- Response rate: 86% (up from 78% in 2023)\n\n**Overall Engagement Score: 72%** (up 4 points from 2023)\n\n**Category Breakdown:**\n\n| Category | 2025 | 2023 | Change |\n|----------|------|------|--------|\n| Job Satisfaction | 74% | 71% | +3 |\n| Manager Relationship | 78% | 75% | +3 |\n| Work-Life Balance | 68% | 62% | +6 |\n| Career Development | 65% | 64% | +1 |\n| Communication | 71% | 68% | +3 |\n| Company Direction | 76% | 72% | +4 |\n\n**Top Strengths:**\n1. \"I feel my work contributes to company success\" (82%)\n2. \"My manager treats me with respect\" (85%)\n3. \"I understand the company's goals\" (79%)\n\n**Areas for Improvement:**\n1. \"I have opportunities for career growth\" (61%)\n2. \"I receive recognition for good work\" (64%)\n3. \"I have access to learning resources\" (63%)\n\n**Action Required:**\n1. Review your department's detailed report (attached)\n2. Schedule team meeting to discuss results\n3. Develop 2-3 department-specific action items\n4. Submit action plan to HR by October 31\n\n**Next Steps:**\n- Department reports distributed: Today\n- Manager Q&A session: October 18, 10 AM\n- Action plans due: October 31\n- Follow-up pulse survey: February 2026\n\nThank you for supporting this initiative.\n\n**Katrin Hoffmann**\nHR Director\nTechBond Industries"
  },
  { // 30-sustainability-kpi.md
    subject: "Sustainability KPI monthly report - October",
    body: "**FROM:** sustainability@techbond.com\n**DATE:** January 04, 2026\n\n---\n\nLeadership Team,\n\nMonthly sustainability performance report for October 2025.\n\n**Executive Summary:**\nOverall sustainability score: **78/100** (target: 75)\nOn track to meet 2025 annual goals.\n\n**Key Performance Indicators:**\n\n**Environmental:**\n| KPI | Target | Actual | Status |\n|-----|--------|--------|--------|\n| Carbon emissions (tCO2e) | 1,200 | 1,150 | On Track |\n| Energy consumption (MWh) | 2,500 | 2,380 | On Track |\n| Water usage (m\u00b3) | 15,000 | 14,200 | On Track |\n| Waste to landfill (%) | <5% | 4.2% | On Track |\n| Recycled content (%) | >30% | 32% | Achieved |\n\n**Social:**\n| KPI | Target | Actual | Status |\n|-----|--------|--------|--------|\n| Safety incidents (LTI) | 0 | 0 | Achieved |\n| Training hours/employee | 20 | 18 | In Progress |\n| Diversity in management | 35% | 33% | In Progress |\n\n**Governance:**\n| KPI | Target | Actual | Status |\n|-----|--------|--------|--------|\n| Supplier audits completed | 50 | 48 | On Track |\n| Ethics training completion | 100% | 96% | In Progress |\n\n**Highlights:**\n- Solar panel installation completed - 15% energy offset\n- Achieved zero waste to landfill in Dusseldorf facility (Sept)\n- New supplier sustainability questionnaire launched\n\n**Challenges:**\n- Training hours behind due to Q3 production demands\n- Two suppliers pending audit rescheduling\n\n**Upcoming:**\n- Carbon neutral certification audit (November)\n- Sustainability report publication (December)\n- 2026 target setting workshop (November 15)\n\nFull report attached.\n\n**Christine Berg**\nSustainability Director\nTechBond Industries"
  }
];

// ============================================================
// MAIN FUNCTION - Run this to seed your inbox
// ============================================================

const WORKSHOP_LABEL = 'TechBond-Workshop-Seed';
const WORKSHOP_MESSAGE_IDS = 'TechBond-Workshop-Seed-MessageIds';

function rememberWorkshopMessage(message) {
  const properties = PropertiesService.getUserProperties();
  const ids = JSON.parse(properties.getProperty(WORKSHOP_MESSAGE_IDS) || '[]');
  ids.push(message.getId());
  properties.setProperty(WORKSHOP_MESSAGE_IDS, JSON.stringify(ids));
}

function sendAllEmails() {
  const me = Session.getActiveUser().getEmail();
  const label = GmailApp.getUserLabelByName(WORKSHOP_LABEL) || GmailApp.createLabel(WORKSHOP_LABEL);
  Logger.log('Seeding ' + EMAILS.length + ' TechBond emails to ' + me + '...');

  let sent = 0;
  EMAILS.forEach((email, index) => {
    try {
      const message = GmailApp.createDraft(me, email.subject, email.body).send();
      message.getThread().addLabel(label);
      rememberWorkshopMessage(message);
      sent++;
      Logger.log('[' + (index + 1) + '/' + EMAILS.length + '] Sent: ' + email.subject);
      Utilities.sleep(500); // gentle rate limit
    } catch (error) {
      Logger.log('[' + (index + 1) + '/' + EMAILS.length + '] FAILED: ' + error.message);
    }
  });

  Logger.log('Done: ' + sent + '/' + EMAILS.length + ' sent. Open gmail.com to see your TechBond inbox.');
}

/**
 * Test function - sends just the first email to verify authorization works
 */
function testSendOneEmail() {
  const me = Session.getActiveUser().getEmail();
  const label = GmailApp.getUserLabelByName(WORKSHOP_LABEL) || GmailApp.createLabel(WORKSHOP_LABEL);
  const message = GmailApp.createDraft(me, 'TEST: ' + EMAILS[0].subject, EMAILS[0].body).send();
  message.getThread().addLabel(label);
  rememberWorkshopMessage(message);
  Logger.log('Test email sent to ' + me + ' - check your inbox!');
}

/** Trash only messages created by this workshop seeder. */
function deleteAllWorkshopEmails() {
  const properties = PropertiesService.getUserProperties();
  const ids = JSON.parse(properties.getProperty(WORKSHOP_MESSAGE_IDS) || '[]');
  const label = GmailApp.getUserLabelByName(WORKSHOP_LABEL);
  if (!ids.length) {
    Logger.log('No recorded workshop seed messages found.');
    return;
  }

  let moved = 0;
  ids.forEach(id => {
    const message = GmailApp.getMessageById(id);
    if (message && !message.isInTrash()) {
      message.moveToTrash();
      moved++;
    }
  });
  properties.deleteProperty(WORKSHOP_MESSAGE_IDS);
  if (label) label.deleteLabel();
  Logger.log('Moved ' + moved + ' recorded workshop seed messages to Trash.');
}
